---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - scaling.core.scaleahead.io
  resources:
  - triggerscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.core.scaleahead.io
  resources:
  - triggerscalings/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.core.scaleahead.io
  resources:
  - triggerscalings/status
  verbs:
  - get
  - patch
  - update
